apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  destination:
    namespace: guestbook
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: guestbook
    helm:
      values: ""
    repoURL: ./app
    targetRevision: "*"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
